### ISSUE TITLE
Cheat mmoitems with crafting items with random attributes

### ISSUE THREAD

**Issue by YKDZ** [WolfyScript/CustomCrafting-Wiki#80]
**Describe the bug**
When a player tries to craft an item with random attributes(such as the one below):
```
NB:
  base:
    material: BOW
    name: '&fNB'
    attack-damage: #<<---------
      base: 7
      scale: 0
      spread: 0.1
      max-spread: 0.5
    arrow-velocity:
      base: 1.8
    revision-id: 0
```
They can refresh the properties of the results by repeatedly removing the components of the workbench.
They can get the best results every time through this.

**Expected behavior**
No matter how to remove components or exit the workbench, they can only get items with a specific value attribute at one time, and they will change to another value next time.

**Screenshots**
https://giphy.com/gifs/KZhKxtU6vhkoqKeS8u

**Server (please complete the following information):**
 - Server Software Purpur
 - Minecraft version 1.18
 - Java version Java17
